name: Release Android CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Setup gradlew
        run: chmod +x android/gradlew

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile

      - name: Get APK Signing Key
        run: echo "$SIGNING_KEY_FILE_HEX" | xxd -r -p - > android/app/release.keystore
        env:
          SIGNING_KEY_FILE_HEX: ${{ secrets.SIGNING_KEY_FILE_HEX }}

      - name: Release APK
        run: npm run release
        env:
          SIGNING_KEY_FILE_HEX: ${{ secrets.SIGNING_KEY_FILE_HEX }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_STORE_PASSWORD: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
